@startuml
set separator none
title Магазин - Containers

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<Магазин.Базаданных>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Магазин.Вебприложение>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Магазин.Клиенты>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Магазин.Корзины>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Покупатель>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Системаобработкизаказов>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Склад>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Магазин.Товары>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
  shadowing false
}
skinparam rectangle<<Магазин>> {
  BorderColor #9a9a9a
  FontColor #9a9a9a
  shadowing false
}

rectangle "==Покупатель\n<size:10>[Person]</size>" <<Покупатель>> as Покупатель
rectangle "==Система обработки заказов\n<size:10>[Software System]</size>\n\nСистема обработки заказов" <<Системаобработкизаказов>> as Системаобработкизаказов
rectangle "==Склад\n<size:10>[Software System]</size>\n\nСистма склада товаров" <<Склад>> as Склад

rectangle "Магазин\n<size:10>[Software System]</size>" <<Магазин>> {
  rectangle "==База данных\n<size:10>[Container: PostgreSQL]</size>\n\nСервис работы с базой данных" <<Магазин.Базаданных>> as Магазин.Базаданных
  rectangle "==Веб-приложение\n<size:10>[Container: Dash, Flask, Python]</size>\n\nСервис, с которым взаимодействует клиент" <<Магазин.Вебприложение>> as Магазин.Вебприложение
  rectangle "==Клиенты\n<size:10>[Container: FastAPI, Python]</size>\n\nСервис работы с данными клиента" <<Магазин.Клиенты>> as Магазин.Клиенты
  rectangle "==Корзины\n<size:10>[Container: FastAPI, Python]</size>\n\nСервис работы с корзинами" <<Магазин.Корзины>> as Магазин.Корзины
  rectangle "==Товары\n<size:10>[Container: FastAPI, Python]</size>\n\nСервис работы со списком доступных товаров" <<Магазин.Товары>> as Магазин.Товары
}

Покупатель .[#707070,thickness=2].> Магазин.Вебприложение : "<color:#707070>Работа с приложением\n<color:#707070><size:8>[HTTPS]</size>"
Магазин.Вебприложение .[#707070,thickness=2].> Магазин.Клиенты : "<color:#707070>Регистрация пользователей\n<color:#707070><size:8>[JSON/HTTPS]</size>"
Магазин.Вебприложение .[#707070,thickness=2].> Магазин.Товары : "<color:#707070>Просмотр списка товаров\n<color:#707070><size:8>[JSON/HTTPS]</size>"
Магазин.Вебприложение .[#707070,thickness=2].> Магазин.Корзины : "<color:#707070>Добавление товаров в корзину\n<color:#707070><size:8>[JSON/HTTPS]</size>"
Магазин.Клиенты .[#707070,thickness=2].> Магазин.Базаданных : "<color:#707070>Запросы к бд\n<color:#707070><size:8>[SQL]</size>"
Магазин.Товары .[#707070,thickness=2].> Магазин.Базаданных : "<color:#707070>Запросы к бд\n<color:#707070><size:8>[SQL]</size>"
Магазин.Корзины .[#707070,thickness=2].> Магазин.Базаданных : "<color:#707070>Запросы к бд\n<color:#707070><size:8>[SQL]</size>"
Склад .[#707070,thickness=2].> Магазин.Товары : "<color:#707070>Передает информацию о доступных на складе твоарах\n<color:#707070><size:8>[JSON/HTTPS]</size>"
Магазин.Корзины .[#707070,thickness=2].> Системаобработкизаказов : "<color:#707070>Передает информацию корзине покупателя в момент оформления заказа\n<color:#707070><size:8>[JSON/HTTPS]</size>"
@enduml