version: "2.0"
services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=1234
    restart: unless-stopped
    ports:
      - "27020:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_MONGODB_URL=mongodb://root:1234@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mxcitn
      - ME_CONFIG_BASICAUTH_PASSWORD=mxcitn
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
  
  data:
    build: ./mdb_service
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - mongo-express
